kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: TVLgeYLofDkrurbARd6Q+nGYQTymX8+on3HGHZiL/Pc=
      - identity: {}
