version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_HOST_PORT}:${UI_PORT_LOCAL}/tcp
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.132.0.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.132.1.0/24